New options and debug output improvements
The option -g git allows one to specify a git path.

The option -X xargs allows one to specify an xargs path.

The git and xargs commands are now in variables ($GIT and $XARGS
respectively).

When showing debug output filenames are double quoted (in case one has
spaces in filenames, unsafe though it is) and the same for the sed
commands (as it can be misleading otherwise especially if there are
spaces in a sed command).

Updated man page and README.md files.

diff --git a/sgit b/sgit
--- a/sgit
+++ b/sgit
@@ -33,9 +33,11 @@
 # - Cody Boone Ferguson (@xexyl)
 #
 
-export SGIT_VERSION="1.0.0-6 04-01-2024" # format: major.minor.patch-release DD-MM-YYYY
+export SGIT_VERSION="1.0.0-7 11-08-2024" # format: major.minor.patch-release DD-MM-YYYY
 
-USAGE="usage: $(basename "$0") [-h] [-V] [-v level] [-x] [-I] [-i extension] [-o sed_option] [-s sed] [-e command] [-n] [-t] [-0] <glob...>
+USAGE="usage: $(basename "$0") [-h] [-V] [-v level] [-x] [-I] [-i extension]
+	    [-o sed_option] [-s sed] [-g git] [-X xargs]
+	    [-e command] [-n] [-t] [-0] <glob...>
 
     -h			    print help and exit
     -V			    print version and exit
@@ -59,6 +61,9 @@ USAGE="usage: $(basename "$0") [-h] [-V] [-v level] [-x] [-I] [-i extension] [-o
 				command at a time
 
     -s sed		    set path to sed
+    -g git		    set path to git
+    -X xargs		    set path to xargs
+
     -e command		    append sed command to list of commands to execute on globs
 
     -n			    dry-run: don't run sed, only show files or sed commands with files
@@ -79,18 +84,19 @@ USAGE="usage: $(basename "$0") [-h] [-V] [-v level] [-x] [-I] [-i extension] [-o
 
 sgit version: $SGIT_VERSION"
 
-# before we do anything check that this is a git repo!
-git status 2>/dev/null 1>&2
-status="$?"
-if [[ "$status" -ne 0 ]]; then
-    echo "$USAGE" 1>&2
-    echo 1>&2
-    echo "$(basename "$0"): ERROR: ${PWD} is not a git repository" 1>&2
-    exit 1
-fi
+# We must make sure we have the tools installed and that they are executable.
+# This is important in case the user overrides the paths OR if the any of the
+# necessary tools are not installed. We do NOT check if xargs supports -0 as at
+# least in some versions (maybe all) of xargs using an invalid option does not
+# exit non-zero so there's not a good way to test.
+
 
 SED="$(type -P sed)"
+GIT="$(type -P git)"
+XARGS="$(type -P xargs)"
 export SED
+export GIT
+export XARGS
 export I_FLAG=
 export TEST_SED_COMMANDS=""
 export VERBOSITY=0
@@ -110,7 +116,7 @@ IFS=$'\t\n'
 
 # parse args
 #
-while getopts :hVv:xIi:o:s:e:nt0 flag; do
+while getopts :hVv:xIi:o:s:g:X:e:nt0 flag; do
     case "$flag" in
     h)	echo "$USAGE" 1>&2
 	exit 2
@@ -129,6 +135,10 @@ while getopts :hVv:xIi:o:s:e:nt0 flag; do
     o)	SED_OPTIONS+=("$OPTARG")
 	;;
     s)	SED="$OPTARG"
+	;;
+    g)	GIT="$OPTARG"
+	;;
+    X)	XARGS="$OPTARG"
 	;;
     e)	SED_COMMANDS+=("$OPTARG")
 	;;
@@ -159,6 +169,18 @@ done
 
 shift $(( OPTIND - 1 ));
 
+# before we do anything check that this is a git repo!
+"$GIT" status 2>/dev/null 1>&2
+status="$?"
+if [[ "$status" -ne 0 ]]; then
+    echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: ${PWD} is not a git repository" 1>&2
+    exit 1
+fi
+
+
+
 # if verbosity > 3 we show sed, backup extensions and options
 if [[ "$VERBOSITY" -gt 3 ]]; then
     echo "debug[4]: sed: $SED" 1>&2
@@ -188,7 +210,7 @@ fi
 
 # firewall
 
-# check that SED_COMMANDS is not empty!
+# check that SED_COMMANDS is not empty if not a dry run!
 if [[ -z "${SED_COMMANDS[*]}" && -z "$DRY_RUN_OPTION" ]]; then
     echo "$USAGE" 1>&2
     echo 1>&2
@@ -197,23 +219,69 @@ if [[ -z "${SED_COMMANDS[*]}" && -z "$DRY_RUN_OPTION" ]]; then
     exit 3
 fi
 
-# check that sed is executable
+# check that sed is an executable file
 if [[ -z "$SED" ]]; then
-    echo "$(basename "$0"): ERROR: sed cannot be empty" 1>&2
-    echo 1>&2
     echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: \$SED cannot be empty" 1>&2
+    echo "NOTE: use the -s sed option to specify a sed command" 1>&2
     exit 3
 elif [[ ! -f "$SED" ]]; then
-    echo "$(basename "$0"): ERROR: sed is not a regular file: $SED" 1>&2
-    echo 1>&2
     echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: sed is not a regular file: $SED" 1>&2
+    echo "NOTE: use the -s sed option to specify a sed command" 1>&2
     exit 3
 elif [[ ! -x "$SED" ]]; then
-    echo "$(basename "$0"): ERROR: sed is not an executable file: $SED" 1>&2
-    echo 1>&2
     echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: sed is not an executable file: $SED" 1>&2
+    echo "NOTE: use the -s sed option to specify a sed command" 1>&2
     exit 3
 fi
+
+# check that git is an executable file
+if [[ -z "$GIT" ]]; then
+    echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: \$GIT cannot be empty" 1>&2
+    echo "NOTE: use the -g git option to specify a git command" 1>&2
+    exit 3
+elif [[ ! -f "$GIT" ]]; then
+    echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: git is not a regular file: $GIT" 1>&2
+    echo "NOTE: use the -g git option to specify a git command" 1>&2
+    exit 3
+elif [[ ! -x "$GIT" ]]; then
+    echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: git is not an executable file: $GIT" 1>&2
+    echo "NOTE: use the -g git option to specify a git command" 1>&2
+    exit 3
+fi
+
+# check that xargs is an executable file
+if [[ -z "$XARGS" ]]; then
+    echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: \$XARGS cannot be empty" 1>&2
+    echo "NOTE: use the -X xargs option to specify an xargs command" 1>&2
+    exit 3
+elif [[ ! -f "$XARGS" ]]; then
+    echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: xargs is not a regular file: $XARGS" 1>&2
+    echo "NOTE: use the -X xargs option to specify an xargs command" 1>&2
+    exit 3
+elif [[ ! -x "$XARGS" ]]; then
+    echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: xargs is not an executable file: $XARGS" 1>&2
+    echo "NOTE: use the -X xargs option to specify an xargs command" 1>&2
+    exit 3
+fi
+
 
 # if we are just testing sed commands we can do that now without checking for
 # globs as we can run sed on an empty string with the same effect. This is why
@@ -250,7 +318,7 @@ fi
 # processed will be shown
 if [[ "$VERBOSITY" -gt 1 ]]; then
     for cmd in "${SED_COMMANDS[@]}"; do
-	echo "debug[2]: sed command: -e $cmd" 1>&2
+	echo "debug[2]: sed command: -e \"$cmd\"" 1>&2
     done
     if [[ "$VERBOSITY" -gt 2 ]]; then
 	echo "debug[2]: looping through all globs" 1>&2
@@ -302,9 +370,9 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 		for cmd in "${SED_COMMANDS[@]}"; do
 		    # check if we should use -z and xargs -0
 		    if [[ -n "$ZERO_FLAG" ]]; then
-			echo "debug[1]: about to run: git ls-files -z $1 | xargs -0 $SED -i\"$EXTENSION\" ${SED_OPTIONS[*]} -e $cmd" 1>&2
+			echo "debug[1]: about to run: $GIT ls-files -z $1 | $XARGS -0 $SED -i\"$EXTENSION\" ${SED_OPTIONS[*]} -e \"$cmd\"" 1>&2
 		    else
-			echo "debug[1]: about to run: git ls-files $1 | xargs $SED -i\"$EXTENSION\" ${SED_OPTIONS[*]} -e $cmd" 1>&2
+			echo "debug[1]: about to run: $GIT ls-files $1 | $XARGS $SED -i\"$EXTENSION\" ${SED_OPTIONS[*]} -e \"$cmd\"" 1>&2
 		    fi
 		done
 
@@ -314,9 +382,9 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 		for cmd in "${SED_COMMANDS[@]}"; do
 		    # check if we should use -z and xargs -0
 		    if [[ "$ZERO_FLAG" ]]; then
-			echo "debug[1]: about to run: git ls-files -z $1 | xargs -0 $SED -i\"$EXTENSION\" -e $cmd" 1>&2
+			echo "debug[1]: about to run: $GIT ls-files -z $1 | $XARGS -0 $SED -i\"$EXTENSION\" -e \"$cmd\"" 1>&2
 		    else
-			echo "debug[1]: about to run: git ls-files $1 | xargs $SED -i\"$EXTENSION\" -e $cmd" 1>&2
+			echo "debug[1]: about to run: $GIT ls-files $1 | $XARGS $SED -i\"$EXTENSION\" -e \"$cmd\"" 1>&2
 		    fi
 		done
 	    fi
@@ -330,9 +398,9 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 		for cmd in "${SED_COMMANDS[@]}"; do
 		    # check for -0
 		    if [[ -n "$ZERO_FLAG" ]]; then
-			echo "debug[1]: about to run: git ls-files -z $1 | xargs -0 $SED ${SED_OPTIONS[*]} -e $cmd" 1>&2
+			echo "debug[1]: about to run: $GIT ls-files -z $1 | $XARGS -0 $SED ${SED_OPTIONS[*]} -e \"$cmd\"" 1>&2
 		    else
-			echo "debug[1]: about to run: git ls-files $1 | xargs $SED ${SED_OPTIONS[*]} -e $cmd" 1>&2
+			echo "debug[1]: about to run: $GIT ls-files $1 | $XARGS $SED ${SED_OPTIONS[*]} -e \"$cmd\"" 1>&2
 		    fi
 		done
 	    # otherwise, if sed options not specified (sgit -o NOT used), we have to show
@@ -341,9 +409,9 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 		for cmd in "${SED_COMMANDS[@]}"; do
 		    # check for -0
 		    if [[ -n "$ZERO_FLAG" ]]; then
-			echo "debug[1]: about to run: git ls-files -z $1 | xargs -0 $SED -e $cmd" 1>&2
+			echo "debug[1]: about to run: $GIT ls-files -z $1 | $XARGS -0 $SED -e \"$cmd\"" 1>&2
 		    else
-			echo "debug[1]: about to run: git ls-files $1 | xargs $SED -e $cmd" 1>&2
+			echo "debug[1]: about to run: $GIT ls-files $1 | $XARGS $SED -e \"$cmd\"" 1>&2
 		    fi
 		done
 	    fi
@@ -361,12 +429,12 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 	# complete
 	if [[ -n "$SED_OPTIONS" ]]; then
 	    # sgit -o used: we have sed options
-	    for f in $(git ls-files "$1" | xargs); do
+	    for f in $("$GIT" ls-files "$1" | "$XARGS"); do
 		if [[ "$VERBOSITY" -ge 1 && -n "${SED_COMMANDS[*]}" ]]; then
 		    # verbosity is high enough: we have sed options so show the
 		    # full sed command
 		    for cmd in "${SED_COMMANDS[@]}"; do
-			echo "$SED" -i"$EXTENSION" "${SED_OPTIONS[*]}" -e "$cmd" "$f" 1>&2
+			echo "debug[1]: $SED" -i"$EXTENSION" "${SED_OPTIONS[*]}" -e \""$cmd"\" \""$f"\" 1>&2
 		    done
 		else
 		    # here verbosity is not high enough (< 1) so we just show
@@ -380,12 +448,12 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 	# depending on the verbosity
 	else
 	    # for each file found with the current glob...
-	    for f in $(git ls-files "$1"); do
+	    for f in $("$GIT" ls-files "$1"); do
 		if [[ "$VERBOSITY" -ge 1 && -n "${SED_COMMANDS[*]}" ]]; then
 		    # verbosity is high enough so we show the sed commands with
 		    # the files found for this glob
 		    for cmd in "${SED_COMMANDS[@]}"; do
-			echo "$SED" -i"$EXTENSION" -e "$cmd" "$f" 1>&2
+			echo "$SED" -i"$EXTENSION" -e \""$cmd"\" \""$f"\" 1>&2
 		    done
 		else
 		    # here we just show the files that would be acted on
@@ -404,11 +472,11 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 	    # check if -0 used
 	    if [[ -n "$ZERO_FLAG" ]]; then
 		for cmd in "${SED_COMMANDS[@]}"; do
-		    git ls-files -z "$1" | xargs -0 "$SED" -i"$EXTENSION" "${SED_OPTIONS[*]}" -e "$cmd"
+		    "$GIT" ls-files -z "$1" | "$XARGS" -0 "$SED" -i"$EXTENSION" "${SED_OPTIONS[*]}" -e "$cmd"
 		done
 	    else
 		for cmd in "${SED_COMMANDS[@]}"; do
-		    git ls-files "$1" | xargs "$SED" -i"$EXTENSION" "${SED_OPTIONS[*]}" -e "$cmd"
+		    "$GIT" ls-files "$1" | "$XARGS" "$SED" -i"$EXTENSION" "${SED_OPTIONS[*]}" -e "$cmd"
 		done
 	    fi
 	else
@@ -418,11 +486,11 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 	    # check if -0 used
 	    if [[ -n "$ZERO_FLAG" ]]; then
 		for cmd in "${SED_COMMANDS[@]}"; do
-		    git ls-files -z "$1" | xargs -0 "$SED" -i"$EXTENSION" -e "$cmd"
+		    "$GIT" ls-files -z "$1" | "$XARGS" -0 "$SED" -i"$EXTENSION" -e "$cmd"
 		done
 	    else
 		for cmd in "${SED_COMMANDS[@]}"; do
-		    git ls-files "$1" | xargs "$SED" -i"$EXTENSION" -e "$cmd"
+		    "$GIT" ls-files "$1" | "$XARGS" "$SED" -i"$EXTENSION" -e "$cmd"
 		done
 	    fi
 	fi
@@ -436,11 +504,11 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 	    # check for -0
 	    if [[ -n "$ZERO_FLAG" ]]; then
 		for cmd in "${SED_COMMANDS[@]}"; do
-		    git ls-files -z "$1" | xargs -0 "$SED" "${SED_OPTIONS[*]}" -e "$cmd"
+		    "$GIT" ls-files -z "$1" | "$XARGS" -0 "$SED" "${SED_OPTIONS[*]}" -e "$cmd"
 		done
 	    else
 		for cmd in "${SED_COMMANDS[@]}"; do
-		    git ls-files "$1" | xargs "$SED" "${SED_OPTIONS[*]}" -e "$cmd"
+		    "$GIT" ls-files "$1" | "$XARGS" "$SED" "${SED_OPTIONS[*]}" -e "$cmd"
 		done
 	    fi
 	else
@@ -449,11 +517,11 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 	    # check for -0
 	    if [[ -n "$ZERO_FLAG" ]]; then
 		for cmd in "${SED_COMMANDS[@]}"; do
-		    git ls-files -z "$1" | xargs -0 "$SED" -e "$cmd"
+		    "$GIT" ls-files -z "$1" | "$XARGS" -0 "$SED" -e "$cmd"
 		done
 	    else
 		for cmd in "${SED_COMMANDS[@]}"; do
-		    git ls-files "$1" | xargs "$SED" -e "$cmd"
+		    "$GIT" ls-files "$1" | "$XARGS" "$SED" -e "$cmd"
 		done
 	    fi
 	fi
