New sgit version - add dry-run option -n
If -n is used then it will do one of two things depending on the
verbosity level: if verbosity is greater than or equal to 1 it will show
the files that would be acted on with the sed(1) commands specified if
the -n option was not used; otherwise it will only show the files that
would be acted on if -n had not been used.

There is a thought that this option will be expanded upon.

Updated man page. The README.md file has not been updated for new
examples but the usage string is updated. This will be corrected at a
later point in time.

Moved error message to AFTER the sgit usage if there is a command line
error.

New version 0.0.14 03-10-2023. Added CHANGES.md file starting with this
new version. The most recent version will be at the top of the file. I
might add previous versions to the file later on.

diff --git a/sgit b/sgit
--- a/sgit
+++ b/sgit
@@ -33,9 +33,9 @@
 # - Cody Boone Ferguson (@xexyl)
 #
 
-export SGIT_VERSION="0.0.13-1 03-10-2023" # format: major.minor.patch-release DD-MM-YYYY
+export SGIT_VERSION="0.0.14-1 03-10-2023" # format: major.minor.patch-release DD-MM-YYYY
 
-USAGE="usage: $(basename "$0") [-h] [-V] [-v level] [-x] [-I] [-i extension] [-o sed_option] [-s sed] [-e command] <glob...>
+USAGE="usage: $(basename "$0") [-h] [-V] [-v level] [-x] [-I] [-i extension] [-o sed_option] [-s sed] [-e command] [-n] <glob...>
 
     -h			    print help and exit
     -V			    print version and exit
@@ -57,6 +57,10 @@ USAGE="usage: $(basename "$0") [-h] [-V] [-v level] [-x] [-I] [-i extension] [-o
 
     -s sed		    set path to sed
     -e command		    append sed command to list of commands to execute on globs
+    -n			    dry-run: only show files that would be modified but do not touch them
+				
+				NOTE: depending on verbosity level, only the files considered will
+				be printed or the sed commands along with the files will be printed
 
 sgit version: $SGIT_VERSION"
 
@@ -65,6 +69,7 @@ export SED
 export I_FLAG=
 export VERBOSITY=0
 export EXTENSION=""
+export DRY_RUN_OPTION=""
 
 # we need an array for sed commands
 declare -a SED_COMMANDS
@@ -76,7 +81,7 @@ IFS=$'\t\n'
 
 # parse args
 #
-while getopts :hVv:xIi:o:s:e: flag; do
+while getopts :hVv:xIi:o:s:e:n flag; do
     case "$flag" in
     h)	echo "$USAGE" 1>&2
 	exit 2
@@ -97,6 +102,8 @@ while getopts :hVv:xIi:o:s:e: flag; do
     s)	SED="$OPTARG"
 	;;
     e)	SED_COMMANDS+=(-e "$OPTARG")
+	;;
+    n)	DRY_RUN_OPTION="-n"
 	;;
     \?) echo "$0: ERROR: invalid option: -$OPTARG" 1>&2
 	exit 3
@@ -120,9 +127,10 @@ shift $(( OPTIND - 1 ));
 
 # check that SED_COMMANDS is not empty!
 if [[ -z "${SED_COMMANDS[*]}" ]]; then
+    echo "$USAGE" 1>&2
+    echo 1>&2
     echo "$(basename "$0"): ERROR: you must specify at least one sed command and one glob" 1>&2
     echo 1>&2
-    echo "$USAGE" 1>&2
     exit 3
 fi
 
@@ -146,9 +154,9 @@ fi
 
 # also check number of remaining args
 if [[ "$#" -eq 0 ]]; then
-    echo "$(basename "$0"): ERROR: you must specify at least one glob" 1>&2
-    echo 1>&2
     echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: you must specify at least one glob" 1>&2
     exit 3
 fi
 
@@ -162,23 +170,6 @@ fi
 
 if [[ $VERBOSITY -gt 1 ]]; then
     echo "debug[2]: sed commands:  ${SED_COMMANDS[*]}" 1>&2
-fi
-
-# This might not the best performance because it does this on all files of the
-# glob rather than only those files matched by the glob with matching text but
-# it's better than it used to be (it used to run git ls-files on the repo for
-# each sed command so the more you had the slower it would become as it had to
-# get the list of files each time!).
-#
-# A better approach would be to somehow use git grep to find files that match
-# but this would complicate the command line (at least in any way I can think of
-# how to do it) so we do it on all files in the repo.
-#
-# But these would possibly require additional args to the command and
-# unnecessarily complicate matters. Anyway it's something of a hack so it
-# doesn't have to be perfect (not that there even is such a thing as perfect).
-#
-if [[ "$VERBOSITY" -gt 1 ]]; then
     echo "debug[2]: looping through all globs" 1>&2
 fi
 
@@ -195,15 +186,14 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 	echo "debug[2]: found glob: $i" 1>&2
     fi
 
-
-    if [[ "$VERBOSITY" -ge 1 ]]; then
+    if [[ "$VERBOSITY" -ge 1 && -z "$DRY_RUN_OPTION" ]]; then
 	if [[ -z "$I_FLAG" ]]; then
+	    # SC2128 (warning): Expanding an array without an index only gives the first element.
+	    # shellcheck disable=SC2128
+	    #
 	    # Determine if any sed options were specified. We only need to know
 	    # if the array is empty or not; we do not need to expand it in the
 	    # check.
-	    #
-	    # SC2128 (warning): Expanding an array without an index only gives the first element.
-	    # shellcheck disable=SC2128
 	    if [[ -n "$SED_OPTIONS" ]]; then
 		echo "debug[1]: about to run: git ls-files $1 | xargs $SED -i\"$EXTENSION\" ${SED_OPTIONS[*]} ${SED_COMMANDS[*]}" 1>&2
 	    else
@@ -218,7 +208,25 @@ while [[ "$i" -lt "$GLOBS" ]]; do
 	fi
     fi
 
-    if [[ -z "$I_FLAG" ]]; then
+    if [[ -n "$DRY_RUN_OPTION" ]]; then
+	if [[ -n "$SED_OPTIONS" ]]; then
+	    for f in $(git ls-files "$1" | xargs); do
+		if [[ "$VERBOSITY" -ge 1 ]]; then
+		    echo "$SED" -i"$EXTENSION" "${SED_OPTIONS[*]}" "${SED_COMMANDS[@]}" "$f" 1>&2
+		else
+		    echo "$f" 1>&2
+		fi
+	    done
+	else
+	    for f in $(git ls-files "$1"); do
+		if [[ "$VERBOSITY" -ge 1 ]]; then
+		    echo "$SED" -i"$EXTENSION" "${SED_COMMANDS[@]}" 1>&2
+		else
+		    echo "$f" 1>&2
+		fi
+	    done
+	fi
+    elif [[ -z "$I_FLAG" ]]; then
 	if [[ -n "$SED_OPTIONS" ]]; then
 	    git ls-files "$1" | xargs "$SED" -i"$EXTENSION" "${SED_OPTIONS[*]}" "${SED_COMMANDS[@]}"
 	else
